version: 2.1

# Define reusable commands
commands:
  setup_gradle:
    description: "Setup Gradle with caching"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle.kts" }}
            - gradle-cache-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-v1-
      - run:
          name: Grant execute permission for gradlew
          command: chmod +x ./gradlew
      - run:
          name: Download dependencies
          command: ./gradlew dependencies

  save_gradle_cache:
    description: "Save Gradle cache"
    steps:
      - save_cache:
          key: gradle-cache-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle.kts" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

# Define jobs
jobs:
  dev-workflow:
    docker:
      - image: cimg/android:2024.01.1-node
    resource_class: large
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2
    steps:
      - setup_gradle
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Build all targets
          command: ./gradlew build
      - run:
          name: Run Kotlin linting
          command: ./gradlew ktlintCheck
      - run:
          name: Run Android lint
          command: ./gradlew lintDebug
      - save_gradle_cache
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: build/reports/ktlint
          destination: ktlint-reports
      - store_artifacts:
          path: build/reports/lint-results-debug.html
          destination: android-lint-report

  main-workflow:
    docker:
      - image: cimg/android:2024.01.1-node
    resource_class: large
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2
    steps:
      - setup_gradle
      - run:
          name: Build all targets
          command: ./gradlew build
      - save_gradle_cache
      - store_artifacts:
          path: build/reports
          destination: reports

# Define workflows
workflows:
  version: 2
  
  # Dev branch workflow: build, test, lint
  dev-branch:
    jobs:
      - dev-workflow:
          filters:
            branches:
              only: dev

  # Main branch workflow: build only
  main-branch:
    jobs:
      - main-workflow:
          filters:
            branches:
              only: main